/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Application;

import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author alexl
 */
public class Rlogin extends javax.swing.JFrame {

    /**
     * Creates new form Rlogin
     */
    
    File f = new File("C:\\Users\\user\\Desktop\\java_Assignment\\Main_Application\\src\\main\\java");
    String userid,userpass;
    int ln;
    SimpleDateFormat Time = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    int attempt;
    Technicion_Software t = new Technicion_Software();
    public Rlogin() {
        initComponents();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("user1.png").getImage().getScaledInstance(50,50, Image.SCALE_SMOOTH));
        lblid.setIcon(imageIcon);
        ImageIcon imageIcon1 = new ImageIcon(new ImageIcon("p1.png").getImage().getScaledInstance(49,50, Image.SCALE_SMOOTH));
        lblp.setIcon(imageIcon1);
        ImageIcon imageIcon2 = new ImageIcon(new ImageIcon("icon.png").getImage().getScaledInstance(260,220, Image.SCALE_SMOOTH));
        lblicon.setIcon(imageIcon2);
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblicon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblp = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        idtxt = new javax.swing.JTextField();
        lbladmin = new javax.swing.JLabel();
        txtp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 194, 198));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 2, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AHHASC");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 2, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APU Hostel Appliances ");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 2, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Service Centre");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(295, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(48, 48, 48)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 74, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );

        lblid.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblid.setText("ID:");

        lblp.setFont(new java.awt.Font("Century Gothic", 2, 18)); // NOI18N
        lblp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblp.setText("Password:");

        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        idtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idtxtKeyPressed(evt);
            }
        });

        lbladmin.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        lbladmin.setForeground(new java.awt.Color(4, 146, 194));
        lbladmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladmin.setText("Admin Login");

        txtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idtxt)
                    .addComponent(txtp, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(lbladmin, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbladmin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblid)
                            .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblp))
                        .addContainerGap(63, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c) || Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            idtxt.setEditable(true);
        }else
        {
            idtxt.setEditable(false);
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtp.requestFocusInWindow();
        }
        
    }//GEN-LAST:event_idtxtKeyPressed
    void countline(){
        try {
            ln =1;
            RandomAccessFile raf = new RandomAccessFile("admin.txt","rw");
            try {
                for(int i =0;raf.readLine()!=null;i++){
                    ln++;
                }
            } catch (IOException ex) {
                Logger.getLogger(Rlogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Rlogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    } //to achieve looping through all file using ln as variable
    
    
    
    
    public String getIdTxt() {
        return idtxt.getText();

    }
    
    public String getPtxt() {
        String pwd = new String(txtp.getPassword());
        return pwd;

    }
    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
                
            //Admin admin1 = new Admin(idtxt.getText(),null);
            //admin1.setP(getPtxt());
            User user = new User(idtxt.getText(),null);
            user.setpw(getPtxt());
            Admin admin1 = new Admin(idtxt.getText(),null);
            countline();
            admin1.setP(getPtxt());
            Timestamp timestamp = new Timestamp(System.currentTimeMillis());
            try {
                // TODO add your handling code here:
                RandomAccessFile raf = new RandomAccessFile("admin.txt","rw");
                try {
                    for(int i=0;i<ln;i+=5){ //if have 5 line for 1 user put 5,6 put 6
                        String userid = raf.readLine().substring(4);
                        String userpass = raf.readLine().substring(10);
                        String utype = raf.readLine().substring(6);
                        if(user.getID().equals(userid) && user.getP().equals(userpass) && utype.equals("MANAGER")){
                            JOptionPane.showMessageDialog(null, "Successfully Login Manager","Registered", JOptionPane.ERROR_MESSAGE);
                            user.writeLogM();
                            /*
                            String filepath1 = f+"\\admin\\log.txt"; // if got out of indexbound problem check for textfile remove extra white blankline.
                            File file1 = new File(filepath1);
                            try{
                                FileWriter writer = new FileWriter(file1,true);
                                writer.append("\n"+ "id::" + admin1.getID() +"\n" + "password::" +admin1.getP() + "\n" + "type::Manager" +"\n" + "Status::Success" + "\n" + "Time::" + Time.format(timestamp));
                                writer.write(System.getProperty("line.separator"));
                                writer.close();
                                
                            } catch(IOException e){
                                e.printStackTrace();
                            } */
                            ManagerInterface newframe = new ManagerInterface();
                            newframe.show();
                            dispose();
                            break;
                        }
                        else if(user.getID().equals(userid) && user.getP().equals(userpass) && utype.equals("TECHNICIAN")){
                            admin1.writeLog();
                            JOptionPane.showMessageDialog(null, "Successfully Login Technician","Registered", JOptionPane.ERROR_MESSAGE);
                            /*
                            String filepath1 = f+"\\admin\\log.txt"; // if got out of indexbound problem check for textfile remove extra white blankline.
                            File file1 = new File(filepath1);
                            try{
                                FileWriter writer = new FileWriter(file1,true);
                                writer.append("\n"+ "id::" + user.getID() +"\n" + "password::" +user.getP() + "\n" + "type::Technician" +"\n" + "Status::Success" + "\n" + "Time::" + Time.format(timestamp));
                                writer.write(System.getProperty("line.separator"));
                                writer.close();
                                
                            } catch(IOException e){
                                e.printStackTrace();
                            } */
                            
                            t.show();
                            dispose();
                            break;
                            
                        }
                        else if(i==(ln-5)){ //meeting the next username 5+1 5 skip then meet but dont add that meeting line
                            try{
                                attempt += 1;
                                user.writeLog(attempt);
                                JOptionPane.showMessageDialog(null, "Incorrect Credentials",null, JOptionPane.ERROR_MESSAGE);
                            /*
                            attempt += 1;
                            JOptionPane.showMessageDialog(null, "Incorrect Credentials",null, JOptionPane.ERROR_MESSAGE);
                            String filepath1 = f+"\\admin\\log.txt"; // if got out of indexbound problem check for textfile remove extra white blankline.
                            File file1 = new File(filepath1);
                            try{
                                FileWriter writer = new FileWriter(file1,true);
                                writer.append("\n"+ "id::" + admin1.getID() +"\n" + "password::" + admin1.getP() + "\n" + "Status::failed" + "\n" + "Time::" + Time.format(timestamp) + "\n" + "Atempt::" + attempt);
                                writer.write(System.getProperty("line.separator"));
                                writer.close();*/
                                if(attempt == 3){
                                    System.out.println(attempt);
                                    idtxt.enable(false);
                                    txtp.enable(false);
                                    loginbutton.setEnabled(false);
                                    JOptionPane.showMessageDialog(null, "You have been blocked from logging in, Please contact Admin for assistant",null, JOptionPane.WARNING_MESSAGE);
                                }
                                
                            } catch(IOException e){
                                e.printStackTrace();
                            }
                            break;
                        }
                        for(int x=1;x<=2;x++){ // how many line to skip for login start from unused line
                            raf.readLine();
                        }
                    }
                    
                    
                } catch (IOException ex) {
                    Logger.getLogger(Rlogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Rlogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        

    }//GEN-LAST:event_loginbuttonActionPerformed
    
    
    private void txtpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            loginbutton.doClick();
        }
    }//GEN-LAST:event_txtpKeyPressed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rlogin().setVisible(true);
            }
            
            
            
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbladmin;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblp;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPasswordField txtp;
    // End of variables declaration//GEN-END:variables
}
